id: A125539A3
title: Guru Yoga of Milarepa Shepa Dorje for Daily Practice
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:41:18.037683
  last_modified_at: 2022-03-01 01:41:18.037691
